version: '3'

services:
  mongo:
    image: mongo:3.2-jessie
    volumes:
      - ./backend/mongo:/data/db
    ports:
      - '27017:27017'
  backend:
    image: dva-backend:local
    volumes:
      - ${PWD}/application_data.json:/app/application_data.json
    ports:
      - '3000:3000'
    tty: true
    command: ["sh", "./wait-for-it.sh", "mongo:27017", "--", "node", "up.js"]